version: "3"

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASS=123123
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:11.18-alpine
    container_name: db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
    - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
    db: